=== Soreepeong/XivAlexander/StaticData/ExcelTransformConfig/exceltransformconfig.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://xivalexander/exceltransformconfig.schema.json",
  "title": "Excel String Transformation Configuration",
  "description": "Describe how to transform cells",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "revision": {
      "type": "integer",
      "default": 1,
      "minimum": 1
    },
    "description": {
      "type": "string"
    },
    "targetLanguage": {
      "type": "string",
      "enum": [
        "Japanese",
        "English",
        "German",
        "French",
        "ChineseSimplified",
        "ChineseTraditional",
        "Korean"
      ]
    },
    "sourceLanguages": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "Japanese",
          "English",
          "German",
          "French",
          "ChineseSimplified",
          "ChineseTraditional",
          "Korean"
        ]
      },
      "minItems": 1,
      "maxItems": 7
    },
    "columnMap": {
      "type": "object",
      "patternProperties": {
        "^(?!#)": {
          "type": "array",
          "items": {
            "type": "integer"
          }
        }
      }
    },
    "pluralMap": {
      "type": "object",
      "patternProperties": {
        "^(?!#)": {
          "type": "array",
          "items": {
            "type": [
              "integer",
              "null"
            ],
            "minItems": 2,
            "maxItems": 4
          }
        }
      }
    },
    "targetGroups": {
      "type": "object",
      "patternProperties": {
        "[^#][A-Za-z0-9]+": {
          "type": [
            "array",
            "integer"
          ],
          "items": {
            "type": [
              "integer"
            ],
            "minItems": 1
          }
        }
      }
    },
    "sourceReplacements": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "from": {
            "type": "string"
          },
          "to": {
            "type": "string"
          }
        }
      }
    },
    "replacementTemplates": {
      "type": "object",
      "patternProperties": {
        "[^#][A-Za-z0-9]+": {
          "type": "object",
          "properties": {
            "from": {
              "type": "string"
            },
            "to": {
              "type": "string"
            }
          }
        }
      }
    },
    "ignoredCells": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "id": {
            "type": "integer"
          },
          "column": {
            "type": "integer"
          },
          "forceLanguage": {
            "type": "string",
            "enum": [
              "Japanese",
              "English",
              "German",
              "French",
              "ChineseSimplified",
              "ChineseTraditional",
              "Korean"
            ]
          }
        },
        "required": [
          "name",
          "id",
          "column"
        ]
      }
    },
    "rules": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "targetGroups": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "replaceTo": {
            "type": "string"
          },
          "stringPattern": {
            "type": "string"
          }
        },
        "required": [
          "targetGroups",
          "replaceTo"
        ]
      }
    }
  },
  "required": [
    "name",
    "targetLanguage",
    "sourceLanguages",
    "targetGroups",
    "rules"
  ]
}

=== Soreepeong/XivAlexander/StaticData/ExcelTransformConfig/CrossRegionRemapping.json
{
  "name": "Maps column across regions.",
  "description": "",
  "targetLanguage": "English",
  "sourceLanguages": [
    "English",
    "Japanese"
  ],
  "columnMap": {
    "^DawnMemberUiParam$": {
      "Japanese": [1],
      "English": [1],
      "German": [1],
      "French": [1],
      "ChineseSimplified": [2],
      "Korean": [2]
    },
    "^DescriptionStandaloneTransient": {
      "Japanese": [1],
      "English": [1],
      "German": [1],
      "French": [1],
      "ChineseSimplified": [0],
      "Korean": [0]
    },
    "^NpcYell$": {
      "Japanese": [10],
      "English": [10],
      "German": [10],
      "French": [10],
      "ChineseSimplified": [9],
      "Korean": [9]
    },
    "^MainCommand": {
      "Japanese": [5, 6],
      "English": [5, 6],
      "German": [5, 6],
      "French": [5, 6],
      "ChineseSimplified": [4, 5],
      "Korean": [4, 5]
    },
    "^Ornament": {
      "Japanese": [9, 11],
      "English": [9, 11],
      "German": [9, 11],
      "French": [9, 11],
      "ChineseSimplified": [7, 9],
      "Korean": [7, 9]
    }
  },
  "pluralMap": {
    "# comment 1": [
      "singularColumnIndex",
      "pluralColumnIndex",
      "optionalCapitalizedColumnIndex",
      "languageSpecificColumnIndex"
    ],
    "# comment 2": "Priority if the language does not have plural forms: optionalCapitalized, singular, plural",
    "^BNpcName$": [0, 2],
    "^BuddyEquip$": [0, 2, 8],
    "^DeepDungeonEquipment$": [1, 3, 9],
    "^DeepDungeonItem$": [1, 3, 9],
    "^DeepDungeonMagicStone$": [1, 3, 9],
    "^ENpcResident$": [0, 2],
    "^EObjName$": [0, 2],
    "^EventItem$": [0, 2, 9],
    "^GatheringPointName$": [0, 2],
    "^GCRank(Gridania|Limsa|Uldah)(Male|Female)Text$": [0, 2],
    "^Item$": [0, 2, 9],
    "^Mount$": [0, 2],
    "^Ornament$": [9, 11],
    "^PlaceName$": [0, 2, null, 8],
    "^Treasure$": [0, 2],
    "^Tribe$": [0, 1]
  },
  "targetGroups": {},
  "rules": []
}
